watermark_image:
  type: upload
  default: ""

watermark_position:
  type: enum
  default: "bottom-right"
  choices:
    - top-left
    - top-center
    - top-right
    - center-left
    - center
    - center-right
    - bottom-left
    - bottom-center
    - bottom-right

watermark_margin_x:
  type: integer
  default: 1

watermark_margin_y:
  type: integer
  default: 1

watermark_opacity:
  type: integer
  default: 100

watermark_scale:
  type: float
  default: 1
  min: 0.1
  max: 10

watermark_rotate:
  type: integer
  default: 0

watermark_blend_mode:
  type: enum
  default: "normal"
  choices:
    - normal
    - overlay
    - over
    - atop
    - xor
    - plus
    - multiply
    - burn
    - difference
    - soft_light
    - screen
    - hard_light
    - dodge
    - exclusion
    - lighten
    - darken

watermark_pattern:
  type: enum
  default: "single"
  choices:
    - single
    - grid
    - diagonal
    - random

watermark_pattern_max_count:
  type: integer
  default: 50

watermark_pattern_spacing:
  type: integer
  default: 15

watermark_pattern_allow_partial:
  type: bool
  default: true

watermark_categories:
  type: list
  list_type: category
  default: ""

watermark_groups:
  type: list
  list_type: group
  default: "0"
