watermark_image:
  type: upload
  default: ""

watermark_qrcode_enabled:
  type: bool
  default: false

watermark_qrcode_text:
  type: string
  default: ""

watermark_qrcode_color:
  type: string
  list_type: color
  default: "var(--primary)"

watermark_qrcode_background_color:
  type: string
  default: "var(--secondary)"

watermark_qrcode_quiet_zone:
  type: integer
  default: 2
  min: 0
  max: 10

watermark_qrcode_error_correction:
  type: enum
  default: "Medium"
  choices:
    - Low
    - Medium
    - Quarter
    - High

watermark_position:
  type: enum
  default: "bottom-right"
  choices:
    - top-left
    - top-center
    - top-right
    - center-left
    - center
    - center-right
    - bottom-left
    - bottom-center
    - bottom-right

watermark_margin_x:
  type: integer
  default: 0

watermark_margin_y:
  type: integer
  default: 0

watermark_opacity:
  type: integer
  default: 100
  min: 1
  max: 100

watermark_size_mode:
  type: enum
  default: "relative"
  choices:
    - relative
    - absolute

watermark_relative_width:
  type: integer
  default: 10
  min: 1
  max: 100

watermark_absolute_scale:
  type: float
  default: 1
  min: 0.01

watermark_max_size:
  type: integer
  default: 100
  min: 1
  max: 100

watermark_rotate:
  type: integer
  default: 0
  min: -360
  max: 360

watermark_blend_mode:
  type: enum
  default: "normal"
  choices:
    - normal
    - overlay
    - over
    - atop
    - xor
    - plus
    - multiply
    - burn
    - difference
    - soft_light
    - screen
    - hard_light
    - dodge
    - exclusion
    - lighten
    - darken

watermark_pattern:
  type: enum
  default: "single"
  choices:
    - single
    - grid
    - diagonal
    - random

watermark_pattern_allow_partial:
  type: bool
  default: true

watermark_pattern_max_count:
  type: integer
  default: 50
  min: 0

watermark_pattern_spacing:
  type: integer
  default: 15

watermark_categories:
  type: list
  list_type: category
  default: ""

watermark_groups:
  type: list
  list_type: group
  default: "0"

watermark_skip_small_images:
  type: bool
  default: false
  description: "Skip watermarking if image is below minimum dimensions"

watermark_min_image_dimensions:
  type: string
  default: "200x200"
  description: "Minimum dimensions required to apply watermark (width x height)"

watermark_allow_non_supported_uploads:
  type: bool
  default: false
